version: '3'

services:
  database:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      apis:
        aliases:
          - mongo

  microservice:
    image: efservice
    ports:
      - "8000:8000"
    networks:
      apis:
        aliases:
          - ef_service

networks:
  apis: {}